version: '3.9'

services:
  backend:
    build: .
    container_name: app-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge 