version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
    container_name: app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/var/www/app/frontend
      - /var/www/app/frontend/node_modules
    command: npm run dev
    networks:
      - appnet

  backend:
    build: 
      context: .
      target: development
    container_name: app-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - db
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
      - ./logs:/var/www/app/logs
    command: npm run dev

  db:
    image: postgres:15-alpine
    container_name: app-db
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: 