version: '3.9'

services:
  frontend:
    build: 
      context: ./src/frontend
      target: production
    container_name: app-frontend-prod
    ports:
      - "80:80"
    networks:
      - appnet

  backend:
    build: 
      context: .
      target: production
    container_name: app-backend-prod
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: app-db-prod
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: 